# workflow from gh-difftoo
name: release

on:
  push:
    tags:
      - "*.[0-9]*.[0-9]*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (test without creating release)"
        required: false
        default: "true"
        type: boolean

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: darwin-amd64
            os: macos-latest
            cargo_build_target: x86_64-apple-darwin
          - target: darwin-arm64
            os: macos-latest
            cargo_build_target: aarch64-apple-darwin
          - target: linux-amd64
            os: ubuntu-latest
            cargo_build_target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    env:
      CARGO_BUILD_TARGET: ${{ matrix.cargo_build_target }}
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - name: Build
        shell: bash
        run: scripts/build_dist.sh release
      - uses: cli/gh-extension-precompile@v2
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && !inputs.dry_run)
        with:
          build_script_override: "scripts/build_dist.sh"
      - name: Update release notes
        if: (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && !inputs.dry_run)) && matrix.target == 'linux-amd64'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git fetch -f origin refs/tags/${{ github.ref_name }}:refs/tags/${{ github.ref_name }}
          NOTES=$(git tag -l --format='%(contents:subject)%0a%0a%(contents:body)' '${{ github.ref_name }}')
          gh release edit '${{ github.ref_name }}' --notes "$NOTES"
